#!/usr/bin/env python3

import os
import shutil
import stat
import sys

THIS_DIR = os.path.dirname(os.path.abspath(__file__))

USER_BIN_DIR = os.path.expanduser("~/.local/bin")
TARGET_BINARY = os.path.join(USER_BIN_DIR, "assvc")

def get_binary_path():
    # Running inside PyInstaller?
    if getattr(sys, "frozen", False):
        # Path inside the temp folder PyInstaller uses
        base_path = sys._MEIPASS
    else:
        base_path = os.path.dirname(os.path.abspath(__file__))

    return os.path.join(base_path, "assvcPackage", "dist", "assvc")

SRC_BINARY = get_binary_path()

def setup(commiter):
    config_path = os.path.expanduser("~/.config/assvc/config")
    os.makedirs(config_path, exist_ok=True)

    with open(config_path + "/commiter", "w") as f:
        f.write(commiter)

def main():
    if not os.path.exists(SRC_BINARY):
        print(f"Error: {SRC_BINARY} not found!")
        return

    os.makedirs(USER_BIN_DIR, exist_ok=True)

    if os.path.realpath(SRC_BINARY) == os.path.realpath(TARGET_BINARY):
        print("Already installed.")
        return

    shutil.copy2(SRC_BINARY, TARGET_BINARY)

    st = os.stat(TARGET_BINARY)
    os.chmod(TARGET_BINARY, st.st_mode | stat.S_IEXEC)

    print(f"Installed to {TARGET_BINARY}")


    if USER_BIN_DIR not in os.environ.get("PATH", ""):
        print("\nAdd this to your shell config if needed:")
        print(f'export PATH="{USER_BIN_DIR}:$PATH"')

    name = input("Enter the username to setup: ")
    setup(name)
    print("\nYou can now run: assvc")



if __name__ == "__main__":
    main()
